// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB4R_HMag6GuKIA_suvNoO79sPX8utxDs',
    appId: '1:961645508859:web:da8a5bef6af12ac350585e',
    messagingSenderId: '961645508859',
    projectId: 'test-5i5',
    authDomain: 'test-5i5.firebaseapp.com',
    storageBucket: 'test-5i5.appspot.com',
    measurementId: 'G-L7VS0C8LWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_UpMYWUiVp19vM9tmd611leVfn07X6yI',
    appId: '1:961645508859:android:fbdc366c59a1d31150585e',
    messagingSenderId: '961645508859',
    projectId: 'test-5i5',
    storageBucket: 'test-5i5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Lm5bYFmYcTfowluHIkPV8uAhWoGNnp0',
    appId: '1:961645508859:ios:5dcd083a9fd9cd3e50585e',
    messagingSenderId: '961645508859',
    projectId: 'test-5i5',
    storageBucket: 'test-5i5.appspot.com',
    iosClientId: '961645508859-vlshvh1rnr97mll18tu38osblble4ivn.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
